import logging
import os

from google import genai
from google.genai import types
from tenacity import (before_sleep_log, retry, retry_if_exception_type,
                      stop_after_attempt, wait_exponential)

from ..utils.media import audio_dict_to_wav, frame_batch_to_mp4, tensor_to_pil

logger = logging.getLogger(__name__)

GEMINI_MODELS = [
    "gemini-2.5-flash",
    "gemini-3-flash-preview",
    "gemini-3.1-flash-lite-preview",
]


class GeminiMultimodalNode:
    """Sends multimodal inputs to Google Gemini and returns the generated text response."""

    @classmethod
    def INPUT_TYPES(cls):
        return {
            "required": {
                "api_key": ("STRING", {
                    "multiline": False,
                    "tooltip": "Your Google Gemini API key. Hidden in the UI for security.",
                }),
                "model": (GEMINI_MODELS, {
                    "tooltip": "The Gemini model to use for inference.",
                }),
                "system_prompt": ("STRING", {
                    "multiline": True,
                    "default": "You are a professional prompt engineer specializing in creating detailed, high-quality image prompts for diffusion models.",
                    "tooltip": "System instruction that defines the model's role and behavior.",
                }),
                "user_prompt": ("STRING", {
                    "multiline": True,
                    "dynamicPrompts": True,
                    "tooltip": "The specific instruction or question for the current inference.",
                }),
                "thinking_mode": (["disabled", "low", "medium", "high"], {
                    "default": "disabled",
                    "tooltip": "Controls deep reasoning depth. Higher levels improve complex analysis but increase latency.",
                }),
                "temperature": ("FLOAT", {
                    "default": 1.0,
                    "min": 0.0,
                    "max": 2.0,
                    "step": 0.01,
                    "tooltip": "Controls randomness in token selection. Lower = more deterministic.",
                }),
                "top_p": ("FLOAT", {
                    "default": 0.95,
                    "min": 0.0,
                    "max": 1.0,
                    "step": 0.01,
                    "tooltip": "Nucleus sampling: limits token pool by cumulative probability.",
                }),
                "top_k": ("INT", {
                    "default": 20,
                    "min": 1,
                    "max": 100,
                    "step": 1,
                    "tooltip": "Limits selection to the K most probable tokens.",
                }),
            },
            "optional": {
                "image": ("IMAGE", {
                    "tooltip": "Primary image input for visual analysis (VQA, captioning).",
                }),
                "style_reference": ("IMAGE", {
                    "tooltip": "Secondary image used exclusively as a stylistic reference for prompt generation.",
                }),
                "audio": ("AUDIO", {
                    "tooltip": "Audio input for multimodal analysis.",
                }),
                "video": ("IMAGE", {
                    "tooltip": "Video as a frame batch (large batch dimension) for spatio-temporal analysis.",
                }),
            },
        }

    RETURN_TYPES = ("STRING",)
    RETURN_NAMES = ("generated_text",)
    OUTPUT_TOOLTIPS = ("The text response generated by the Gemini model.",)
    FUNCTION = "generate_response"
    CATEGORY = "Gemini"
    DESCRIPTION = "Sends multimodal inputs (text, images, audio, video) to Google Gemini and returns the generated text response. Designed to create complex image prompts for downstream diffusion models."
    SEARCH_ALIASES = ["gemini", "google", "llm", "vlm", "multimodal", "prompt generator"]

    @classmethod
    def IS_CHANGED(cls, **kwargs):
        return float("NaN")

    def generate_response(
        self,
        api_key,
        model,
        system_prompt,
        user_prompt,
        thinking_mode,
        temperature,
        top_p,
        top_k,
        image=None,
        style_reference=None,
        audio=None,
        video=None,
    ):
        if not api_key or not api_key.strip():
            raise ValueError(
                "Gemini API key is required. Please enter a valid API key."
            )

        client = genai.Client(api_key=api_key.strip())

        temp_files = []
        try:
            # --- Build contents list ---
            contents = []

            # User prompt text
            contents.append(user_prompt)

            # Primary image
            if image is not None:
                pil_image = tensor_to_pil(image)
                contents.append(pil_image)

            # Style reference with in-context learning anchor
            if style_reference is not None:
                pil_style = tensor_to_pil(style_reference)
                contents.append(
                    "The following image is to be used exclusively as a stylistic "
                    "reference for your analysis and generation. Do not describe this "
                    "image as the primary subject — instead, adopt its visual style, "
                    "color palette, and artistic qualities."
                )
                contents.append(pil_style)

            # Audio via Files API
            if audio is not None:
                wav_path = audio_dict_to_wav(audio)
                temp_files.append(wav_path)
                uploaded_audio = client.files.upload(file=wav_path)
                contents.append(
                    types.Part.from_uri(
                        file_uri=uploaded_audio.uri,
                        mime_type=uploaded_audio.mime_type or "audio/wav",
                    )
                )

            # Video via Files API
            if video is not None:
                mp4_path = frame_batch_to_mp4(video)
                temp_files.append(mp4_path)
                uploaded_video = client.files.upload(file=mp4_path)
                contents.append(
                    types.Part.from_uri(
                        file_uri=uploaded_video.uri,
                        mime_type=uploaded_video.mime_type or "video/mp4",
                    )
                )

            # --- Build configuration ---
            config_kwargs = {
                "system_instruction": system_prompt,
                "temperature": temperature,
                "top_p": top_p,
                "top_k": top_k,
            }

            if thinking_mode != "disabled":
                config_kwargs["thinking_config"] = types.ThinkingConfig(
                    thinking_level=thinking_mode,
                )

            config = types.GenerateContentConfig(**config_kwargs)

            # --- Execute inference with retry ---
            response = self._call_api_with_retry(client, model, contents, config)

            # Log usage metadata if available
            if hasattr(response, "usage_metadata") and response.usage_metadata:
                meta = response.usage_metadata
                logger.info(
                    "Gemini usage — prompt tokens: %s, response tokens: %s, total: %s",
                    getattr(meta, "prompt_token_count", "N/A"),
                    getattr(meta, "candidates_token_count", "N/A"),
                    getattr(meta, "total_token_count", "N/A"),
                )

            return (response.text,)

        finally:
            # Cleanup temp files
            for path in temp_files:
                try:
                    os.remove(path)
                    logger.info("Cleaned up temp file: %s", path)
                except OSError as e:
                    logger.warning("Failed to clean up temp file %s: %s", path, e)

    @staticmethod
    @retry(
        wait=wait_exponential(multiplier=2, min=2, max=60),
        stop=stop_after_attempt(5),
        retry=retry_if_exception_type(Exception),
        before_sleep=before_sleep_log(logger, logging.WARNING),
        reraise=True,
    )
    def _call_api_with_retry(client, model, contents, config):
        """Call the Gemini API with exponential backoff retry logic."""
        return client.models.generate_content(
            model=model,
            contents=contents,
            config=config,
        )
